// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides pre-5.7 stub bodies for UFUNCTIONs whose real implementations
// are gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this
// entire file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeGeometryLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

// Stubs land here once Phase 2 introduces the first UFUNCTIONs and
// `python tools/gen_version_stubs.py` regenerates this file.

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
