// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgePCGLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

TArray<FString> UUnrealBridgePCGLibrary::ListPCGGraphAssets(const FString& Filter, int32 Max)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::ListPCGGraphAssets requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

TArray<FBridgePCGComponentEntry> UUnrealBridgePCGLibrary::ListPCGComponentsInLevel(const FString& LevelFilter, int32 Max)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::ListPCGComponentsInLevel requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgePCGComponentEntry>{};
}

FBridgePCGComponentState UUnrealBridgePCGLibrary::GetPCGComponentState(const FString& ActorLabel, const FString& ComponentName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::GetPCGComponentState requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePCGComponentState{};
}

TArray<FBridgePCGOverrideEntry> UUnrealBridgePCGLibrary::GetPCGComponentOverrides(const FString& ActorLabel, const FString& ComponentName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::GetPCGComponentOverrides requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgePCGOverrideEntry>{};
}

bool UUnrealBridgePCGLibrary::SetPCGComponentOverride(const FString& ActorLabel, const FString& ComponentName, const FString& Name, const FString& ExportedValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::SetPCGComponentOverride requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgePCGLibrary::TriggerPCGGenerate(const FString& ActorLabel, const FString& ComponentName, bool bForce)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::TriggerPCGGenerate requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgePCGWaitResult UUnrealBridgePCGLibrary::WaitForPCGGenerate(const FString& ActorLabel, const FString& ComponentName, float TimeoutSec)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::WaitForPCGGenerate requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePCGWaitResult{};
}

bool UUnrealBridgePCGLibrary::CleanupPCGComponent(const FString& ActorLabel, const FString& ComponentName, bool bRemoveComponents)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::CleanupPCGComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
